# Generated by Django 3.2.9 on 2021-11-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Alarm')),
                ('desc', models.TextField(blank=True, max_length=1000, verbose_name='ToDo')),
                ('alarm_date', models.DateTimeField(blank=True, verbose_name='ToAlarm')),
            ],
            options={
                'verbose_name': 'Alarm',
                'verbose_name_plural': 'Alarms',
                'ordering': ['alarm_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Task')),
                ('desc', models.TextField(blank=True, max_length=1000, verbose_name='Desc')),
                ('dead_line', models.DateField(blank=True, verbose_name='Finish')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['title'],
            },
        ),
    ]
